project:
  type: website
  output-dir: public

website:
  title: Piney Data | Your Source For Evergreen Analytics
  favicon: img/favicon.ico
  site-url: https://www.pineydata.com
  google-analytics: "G-W0BCPGTRZ6"











